public_ip: 26.44.52.44
database:
  host: localhost
  port: 3306
  name: games
server:
  port: 8098

spring:
  application:
    name: game-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${database.host}:${database.port}/${database.name}
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
  web:
    resources:
      static-locations: file:C:\Users\Omar Marrakchi\Desktop\gamemax marketplace-service\gamemax\Services\game-service\uploads\gameImages\
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
eureka:
  instance:
    hostname: ${public_ip}
    prefer-ip-address: false
    instance-id: ${public_ip}:${server.port}