public_ip: 26.223.72.183
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: raslenm39@gmail.com
    password: lkymptuqaadxngrj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5

  # Serveur pour les fichiers statiques
  web:
    resources:
      static-locations: "file:/C:/Users/user/Desktop/Pi dev/projet dev gamemax/gestion-de-user-for-Pi-BACKEND--main/Services/user-service/uploads/"

logging:
  level:
    org.springframework: DEBUG   # Debug Spring Framework logs
    org.hibernate.SQL: DEBUG       # Debug Hibernate SQL queries
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE  # Debug SQL parameter binding
    com.gamax.userservice: DEBUG   # Debug logs for your application (replace with your package name)

security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 3600000  # 1h in milliseconds

server:
  error:
    whitelabel:
      enabled: false  # Disable Whitelabel Error Page
    path: /error      # Path to the error controller
  # Configuration du port du serveur (si tu veux le modifier)
  port: 8091


ai:
  service:
    api:
      key: AIzaSyD2ZNSI6TVI53L7IW16kvWggWelyFucQ9w
      url: https://generativelanguage.googleapis.com/v1



eureka:
  instance:
    hostname: ${public_ip}
    prefer-ip-address: false
    instance-id: ${public_ip}:${server.port}